### ISSUE TITLE
Route Id format

### ISSUE THREAD

**Issue by dragoon** [geops/gtfsparser#2]
Hello, could you please explain how route ids are generated?
I'm working with the Swiss GTFS data produced by geops.ch and it seems that the route with the same name has multiple ids assigned to it. At the moment it seems that the route id is actually the trip id.

**Comment by patrickbr** [comment]
Only some trips are grouped into routes in our feed. The raw dataset we generate the GTFS feed from doesn't really have anything that maps to the concept of "routes" in GTFS. Since GTFS discourages, but allows even the extreme case of a 1:1 relationship between trips and routes, we chose to only group trips into routes where the raw data also does it. This makes for a slightly bigger dataset, but prevents possibly wrong interpretations of the raw data by an automatic grouping.

**Comment by patrickbr** [comment]
PS: the [documentation](http://gtfs.geops.de/doc/) (only available in german) describes the route id generation in detail.

**Comment by dragoon** [comment]
Thanks a lot for the explanation, perhaps you would be interested to take a look at the GTFS data released by SBB recently (they also do some conversion from HAFAS):
https://opentransportdata.swiss/en/dataset/timetable-2017-gtfs
